image: gcc

google-tests:
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install cmake autoconf
  script:
    - mkdir parser_build
    - cd parser_build
    - cmake ../Parser_Test
    - cmake --build .
    - ./parser_tests --gtest_output="xml:report.xml"


linting:
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install cmake autoconf
    - apt-get -y install clang clang-tidy clang-format
  script:
    - cd Parser
    - clang-tidy *.cpp --
    - clang *.cpp -fsyntax-only
    