stages:
  - build
  - test

image: ubuntu:latest    

build_install:
  stage: build
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  before_script:
    - apt-get update
    - apt-get -y install gcc g++ cmake autoconf git
  script:
    - echo "Install complete."


unit_testing:
  stage: test
  needs: [build_install]
  script:
    - mkdir parser_build
    - cd parser_build
    - cmake ../Parser_Test
    - cmake --build .
    - ./parser_tests --gtest_output="xml:report.xml"
    
    
integration_testing:
  stage: test
  needs: [build_install]
  before_script:
    - wget http://131.123.42.38/lmcrs/v1.0.0/srcml_1.0.0-1_ubuntu18.04.deb
    - apt-get -y install ./srcml_1.0.0-1_ubuntu18.04.deb
  script:
    - cd StandAlone
    - mkdir build
    - cd build
    - cmake ../
    - cmake --build .
    - ./parser_standalone ../../Parser_Test/Integration/data
    - cd ../../Parser_Test/Integration
    - cmake .
    - cmake --build .
    - ./parser_tests_integration --gtest_output="xml:report.xml"


linting:
  stage: test
  needs: [build_install]
  before_script:
    - apt-get -y install clang clang-tidy clang-format
  script:
    - cd Parser
    - clang-tidy *.cpp -- 
    - clang *.cpp -fsyntax-only -Werror