stages:
  - build
  - test

image: ubuntu:latest    

build_install:
  stage: build
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  before_script:
    - apt-get update
    - apt-get -y install gcc g++ cmake autoconf git
  script:
    - echo "Install complete."
    - mkdir build
    - cd build
    - cmake ../
    - cmake --build .
  artifacts:
    paths:
      - build/StandAlone/parser_standalone
      - build/Parser_Test/parser_tests
      - build/Parser_Test/Integration/parser_tests_integration
      - build/Parser_Test/Integration/data
    expire_in: 1 day
      
  


unit_testing:
  stage: test
  needs: [build_install]
  script:
    - build/Parser_Test/parser_tests --gtest_output="xml:report.xml"
    
    
integration_testing:
  stage: test
  needs: [build_install]
  before_script:
    - apt-get update
    - apt-get -y install wget
    - wget http://131.123.42.38/lmcrs/v1.0.0/srcml_1.0.0-1_ubuntu18.04.deb
    - apt-get -y install ./srcml_1.0.0-1_ubuntu18.04.deb
  script:
    - build/Parser_Test/Integration/parser_tests_integration --gtest_output="xml:report.xml"


linting:
  stage: test
  needs: [build_install]
  before_script:
    - apt-get update
    - apt-get -y install clang clang-tidy clang-format
  script:
    - cd Parser
    - clang-tidy *.cpp -- 
    - clang *.cpp -fsyntax-only -Werror