image: gcc

google-tests:
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install cmake autoconf
  script:
    - mkdir parser_build
    - cd parser_build
    - cmake ../Parser_Test
    - cmake --build .
    - ./parser_tests --gtest_output="xml:report.xml"


linting:
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install cmake autoconf
    - apt-get -y install clang
#    - git clone https://github.com/llvm/llvm-project.git
#    - cd llvm-project
#    - mkdir build
#    - cd build
#    - cmake -DLLVM_ENABLE_PROJECTS=clang -G "Unix Makefiles" ../llvm
#    - make
  script:
    - cd Parser
    - clang *.cpp -fsyntax-only
    - make check-clang
    