image: gcc

integration:
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install cmake autoconf
    - wget http://131.123.42.38/lmcrs/v1.0.0/srcml_1.0.0-1_ubuntu20.04.tar.gz
    - mkdir srcml
    - cd srcml
    - tar xvzf srcml_1.0.0-1_ubuntu20.04.tar.gz
    - ./configure
    - make
    - make install
  script:
    - cd StandAlone
    - mkdir build
    - cd build
    - cmake ../
    - cmake --build .
    - ./parser_standalone

google-tests:
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install cmake autoconf
  script:
    - mkdir parser_build
    - cd parser_build
    - cmake ../Parser_Test
    - cmake --build .
    - ./parser_tests --gtest_output="xml:report.xml"


linting:
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install cmake autoconf
    - apt-get -y install clang clang-tidy clang-format
  script:
    - cd Parser
    - clang-tidy *.cpp --
    - clang *.cpp -fsyntax-only

