image: gcc

google-tests:
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install cmake autoconf
  script:
    - mkdir parser_build
    - cd parser_build
    - cmake ../Parser_Test
    - cmake --build .
    - ./parser_tests --gtest_output="xml:report.xml"


linting:
  stage: test
  before_script:
    - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key| apt-key add -
    - apt-get -y install clang-12 lldb-12 lld-12
  script:
    - echo "succes"
    