name: Testing pipeline
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
             sudo apt-get -qq update
             sudo apt-get -y -qq install gcc g++ cmake autoconf git libantlr4-runtime-dev libantlr4-runtime4.8
      - name: Build
        run: |
             mkdir build
             cd build
             cmake ../
             cmake --build .
      - name: Create artefacts
        uses: actions/upload-artifact@v2
        with:
          name: build_install
          path: |
                build/SearchSECOParser/SearchSECOParserStandalone
                build/tests/parser_tests
          retention-days: 1

  Unit-tests:
    runs-on: ubuntu-latest
    needs: [Build]    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build_install
      - name: Tests
        run: |
             sudo chmod +x tests/parser_tests
             tests/parser_tests --gtest_output="xml:report.xml"
             
  Linting:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build_install
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
             sudo apt-get -qq update
             sudo apt-get -y -qq install clang clang-tidy clang-format
      - name: Run linting
        run: |
             cd libSearchSECOParser
             clang-tidy *.cpp -- -I../external/antlr/src
             clang *.cpp -I../external/antlr/src -fsyntax-only -Werror